[package]
name = "geo-aid"
description = "A tool designed to generate geometrical figures based on given rules."
version = "0.2.6"
edition = "2021"
license = "MIT"
repository = "https://github.com/DragonGamesStudios/Geo-AID/tree/v0.2"

[dependencies]
rand = "0.8.5"
clap = {version = "4.0.32", features = ["derive"]}
crossterm = "0.27.0"
serde = {version = "1.0.151", features = ["derive", "rc"]}
serde_json = "1.0"
strsim = "0.10.0"
geo_aid_derive = { version = "0.1.2", path = "../geo_aid_derive" }
clap-markdown = "0.1.3"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                
    "fast-rng",          
    "macro-diagnostics", 
    "serde",
]
