[package]
name = "geo-aid"
description = "A tool designed to generate geometrical figures based on given rules."
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"
svg = "0.10.0"