[package]
name = "geo-aid"
description = "A tool designed to generate geometrical figures based on given rules."
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"
serde = {version = "1.0.151", features = ["derive"]}
serde_json = "1.0"