[package]
name = "geo-aid-figure"
version = "0.4.1"
edition = "2021"
description = "Definitions for Geo-AID's JSON export format."
license = "MIT"
repository = "https://github.com/Geo-AID/geo-aid"

[dependencies]
