[package]
name = "geo-aid-json"
description = "Support for JSON output from Geo-AID."
version = "0.7.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/Geo-AID/Geo-AID"

[dependencies]
geo-aid-figure = { version = "0.7.1", path = "../geo-aid-figure" }
serde_json = "1.0.128"
