[package]
name = "geo-aid-svg"
description = "Support for SVG output from Geo-AID."
version = "0.6.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Geo-AID/Geo-AID"

[dependencies]
geo-aid-figure = { version = "0.6.0", path = "../geo-aid-figure" }
