[package]
name = "geo-aid-plaintext"
description = "Support for plaintext output from Geo-AID."
version = "0.5.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/Geo-AID/Geo-AID"

[dependencies]
geo-aid-figure = { version = "0.5.1", path = "../geo-aid-figure" }
